/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.elisha.dialog;

import com.elisha.database.Database;
import com.elisha.dialog.panel.UpdateProductInfo;
import com.elisha.gui.Home;
import com.elisha.loggers.Loggers;
import com.elisha.optionpane.Message;
import com.elisha.validator.UserValidate;
import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.SwingUtilities;

/**
 *
 * @author Sanuga
 */
public class UpdateProductDialog extends javax.swing.JDialog {

    /**
     * Creates new form UpdateProductDialog
     */
    private UpdateProductInfo updateInfo;
    private CardLayout contentPanelLayout;
    private static final String cls = UpdateProductDialog.class.getName();
    
    public UpdateProductDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadPanels();
    }
    
    private void loadPanels(){
        
      if(contentPanelLayout == null && productContentPanel.getLayout() instanceof CardLayout){
         contentPanelLayout = (CardLayout) productContentPanel.getLayout();
      }
      
      updateInfo = new UpdateProductInfo();
      
      productContentPanel.add(updateInfo, "update_info");
      SwingUtilities.updateComponentTreeUI(productContentPanel);
    }  

    public void setData(String sku) {
    if (updateInfo != null) {
        updateInfo.setProductBySKU(sku); // use the existing panel
        if (contentPanelLayout != null) {
            contentPanelLayout.show(productContentPanel, "update_info");
        }
        SwingUtilities.updateComponentTreeUI(productContentPanel);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        controlBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        productContentPanel = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(60, 63, 65));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel1.setText("Product Information");

        controlBtn.setBackground(new java.awt.Color(255, 112, 92));
        controlBtn.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        controlBtn.setForeground(new java.awt.Color(255, 255, 255));
        controlBtn.setText("Submit");
        controlBtn.setFocusPainted(false);
        controlBtn.setPreferredSize(new java.awt.Dimension(76, 33));
        controlBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controlBtnActionPerformed(evt);
            }
        });

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        productContentPanel.setBackground(new java.awt.Color(255, 255, 255));
        productContentPanel.setLayout(new java.awt.CardLayout());
        jScrollPane2.setViewportView(productContentPanel);

        backBtn.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        backBtn.setText("Back");
        backBtn.setEnabled(false);
        backBtn.setFocusPainted(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(controlBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(controlBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void controlBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controlBtnActionPerformed
          insertProductData();
    }//GEN-LAST:event_controlBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

    }//GEN-LAST:event_backBtnActionPerformed

    private synchronized void insertProductData(){
    
        String productName = updateInfo.getPrNameInput().getText();
        String description = updateInfo.getPrDescriptionInput().getText();
        int status = updateInfo.getPrStatusCombo().getSelectedIndex();
        String sku = updateInfo.getPrSKUInput().getText();

        UserValidate validate = new UserValidate();
        Message msg = new Message();

        if (!validate.isEmpty(productName)) {
            msg.showError(this, "Product Name Can't be Empty");
            return;
        }
        if (!validate.isEmpty(description)) {
            msg.showError(this, "Product Description Can't be Empty");
            return;
        }

        try (Connection connection = Database.createConnection()) {
            if (connection != null) {

                String updateProductSQL = "UPDATE `product` SET `title` = ?, `description` = ?, `status_id` = ? WHERE `product_sku` = ?";

                if(status == 1){
                  status = 2;
                }else if(status == 0){
                  status = 1;
                }else{
                  status = 0;
                }
                
                int productRows = 0;

                try (PreparedStatement psProduct = connection.prepareStatement(updateProductSQL)) {

                    // update product
                    psProduct.setString(1, productName);
                    psProduct.setString(2, description);
                    psProduct.setInt(3, status);
                    psProduct.setString(4, sku);
                    
                    productRows = psProduct.executeUpdate();
                    
                    if (productRows > 0) {
                        msg.showSucess(this, "Product Successfully Updated");
                        this.dispose();
                    } else {
                        msg.showError(this, "No records were updated. Please check SKU or data.");
                        this.dispose();
                    }
                } catch (SQLException e) {
                    Loggers.logInfo("Update failed: " + e.getMessage(), cls);
                    msg.showError(this, "Error updating product.");
                }
            }
        } catch (SQLException e) {
            Loggers.logInfo(e.getMessage(), cls);
            msg.showError(this, "Database connection error.");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try{
           FlatIntelliJLaf.setup();
        }catch(Exception e){
            Loggers.logInfo("Failed to Load Theme: "+e.getMessage() ,  cls);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateProductDialog dialog = new UpdateProductDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton controlBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel productContentPanel;
    // End of variables declaration//GEN-END:variables
}
