/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.elisha.dialog.panel;

import com.elisha.session.UserSession;
import java.util.Random;
import java.sql.*;
import java.lang.ClassNotFoundException;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Sanuga
 */
public class BasicProductInfoPanel extends javax.swing.JPanel {

    /**
     * Creates new form BasicProductInfoPanel
     */
    private HashMap<String, Integer> brandMap;
    private HashMap<String, Integer> categoryMap;
    private HashMap<String, Integer> genderMap;
    private HashMap<String, Integer> statusMap;
    private HashMap<String, Integer> userTypeMap;

    public BasicProductInfoPanel() {
        initComponents();
        this.brandMap = new HashMap<>();
        this.categoryMap = new HashMap<>();
        this.genderMap = new HashMap<>();
        this.statusMap = new HashMap<>();
        this.userTypeMap = new HashMap<>();
        loadBrand();
        loadCategory();
        generateSKUNumebr();
        loadAddedby();
    }
    
    private ResultSet searchData(String query){
      ResultSet rs = null;
        try{
        
            try{
              Class.forName("com.mysql.cj.jdbc.Driver");
               Connection c = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/elisha_db", "root", "2006@Sanuga");
               Statement smt = c.createStatement();
               rs = smt.executeQuery(query);
            }catch(ClassNotFoundException e){
               e.printStackTrace();
            }
        }catch(SQLException e){
          e.printStackTrace();
        }
        return rs;
    }

    private void loadCategory(){
        try{
            ResultSet rs = searchData("SELECT * FROM `category`");
            Vector<String> categories = new Vector();
            categories.add("Select Category");
            categoryMap.put("Select Category",0);
            while(rs.next()){
              String categoriesName = rs.getString("name");
              categoryMap.put(categoriesName, rs.getInt("id"));
              categories.add(categoriesName);
            }
            DefaultComboBoxModel dcm = new DefaultComboBoxModel(categories);
            prCatCombo.setModel(dcm);
        }catch(SQLException e){
          e.printStackTrace();
        }
    }
    
    private void loadAddedby(){

        Vector<String> added = new Vector();
        added.add(UserSession.name);
        
        DefaultComboBoxModel dcm = new DefaultComboBoxModel<>(added);
        prGenderCombo.setModel(dcm);
    
    }
    
    private void loadBrand(){
        try{
            ResultSet rs = searchData("SELECT * FROM `brand`");
            Vector<String> brands = new Vector();
            brands.add("Select Brands");
            brandMap.put("Select Brand",0);
            while(rs.next()){
              String brandName = rs.getString("brand");
              brandMap.put(brandName, rs.getInt("id"));
              brands.add(brandName);
            }
            DefaultComboBoxModel dcm = new DefaultComboBoxModel(brands);
            prBrandCombo.setModel(dcm);
        }catch(SQLException e){
          e.printStackTrace();
        }
    }

    public HashMap<String, Integer> getBrandMap() {
        return brandMap;
    }

    public HashMap<String, Integer> getCategoryMap() {
        return categoryMap;
    }

    public HashMap<String, Integer> getGenderMap() {
        return genderMap;
    }

    public HashMap<String, Integer> getStatusMap() {
        return statusMap;
    }

    public HashMap<String, Integer> getUserTypeMap() {
        return userTypeMap;
    }
    
    private void generateSKUNumebr(){
    
        Random rand = new Random();

        int numberPart = rand.nextInt(90000) + 10000;

        char letterPart = (char) (rand.nextInt(26) + 'A');

        String skunumber = "SKU-" + numberPart + letterPart;
        prSKUInput.setText(skunumber);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        prNameInput = new javax.swing.JTextField();
        prSKUInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        prDescriptionInput = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        prCatCombo = new javax.swing.JComboBox<>();
        prBrandCombo = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        prGenderCombo = new javax.swing.JComboBox<>();
        prStatusCombo = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(520, 365));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(2, 2, 10, 5));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2.setText("Product Name");
        jPanel2.add(jLabel2);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel3.setText("Product SKU Name");
        jPanel2.add(jLabel3);

        prNameInput.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        prNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prNameInputActionPerformed(evt);
            }
        });
        jPanel2.add(prNameInput);

        prSKUInput.setEditable(false);
        prSKUInput.setBackground(new java.awt.Color(255, 255, 255));
        prSKUInput.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        prSKUInput.setEnabled(false);
        jPanel2.add(prSKUInput);

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel4.setText("Product Description");

        prDescriptionInput.setColumns(20);
        prDescriptionInput.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        prDescriptionInput.setRows(5);
        jScrollPane2.setViewportView(prDescriptionInput);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(2, 2, 10, 5));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel1.setText("Product Category");
        jPanel1.add(jLabel1);

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel5.setText("Product Brand");
        jPanel1.add(jLabel5);

        prCatCombo.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        prCatCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prCatComboActionPerformed(evt);
            }
        });
        jPanel1.add(prCatCombo);

        prBrandCombo.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jPanel1.add(prBrandCombo);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridLayout(2, 2, 10, 5));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel6.setText("Added By");
        jPanel4.add(jLabel6);

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel7.setText("Product Status");
        jPanel4.add(jLabel7);

        prGenderCombo.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        prGenderCombo.setEnabled(false);
        jPanel4.add(prGenderCombo);

        prStatusCombo.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        prStatusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active ", "Inactive" }));
        prStatusCombo.setEnabled(false);
        jPanel4.add(prStatusCombo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void prNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prNameInputActionPerformed

    private void prCatComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prCatComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prCatComboActionPerformed

    public JComboBox<String> getPrBrandCombo() {
        return prBrandCombo;
    }

    public JComboBox<String> getPrCatCombo() {
        return prCatCombo;
    }

    public JTextArea getPrDescriptionInput() {
        return prDescriptionInput;
    }

    public JComboBox<String> getPrGenderCombo() {
        return prGenderCombo;
    }

    public JTextField getPrNameInput() {
        return prNameInput;
    }

    public JTextField getPrSKUInput() {
        return prSKUInput;
    }

    public JComboBox<String> getPrStatusCombo() {
        return prStatusCombo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> prBrandCombo;
    private javax.swing.JComboBox<String> prCatCombo;
    private javax.swing.JTextArea prDescriptionInput;
    private javax.swing.JComboBox<String> prGenderCombo;
    private javax.swing.JTextField prNameInput;
    private javax.swing.JTextField prSKUInput;
    private javax.swing.JComboBox<String> prStatusCombo;
    // End of variables declaration//GEN-END:variables
}
