/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.elisha.dialog.panel;

import java.awt.Image;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;


/**
 *
 * @author Sanuga
 */
public class ProductImagePanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductImagePanel
     */
    public ProductImagePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        prImagePathInput = new javax.swing.JTextField();
        imageLoadingPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        prImagePathInput.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        prImagePathInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prImagePathInputActionPerformed(evt);
            }
        });

        imageLoadingPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(prImagePathInput, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(imageLoadingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prImagePathInput, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imageLoadingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void prImagePathInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prImagePathInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prImagePathInputActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        JFileChooser jf = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Images (.png, .jpg, .jpeg)", "png","jpg","jpeg");
        jf.setFileFilter(filter);
        int option = jf.showOpenDialog(imageLoadingPanel);
        if(option == JFileChooser.APPROVE_OPTION){
            File selectedFile  = jf.getSelectedFile();
            try{
              
                File imageFolder = new File("Product Images");
                
                if(!imageFolder.exists()){
                   imageFolder.mkdir();
                }
                
                String fileName = System.currentTimeMillis() + "_" + selectedFile.getName();
                File destinationFile = new File(imageFolder, fileName);
                prImagePathInput.setText(destinationFile.getAbsolutePath());
                Files.copy(selectedFile.toPath(), destinationFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
                showImage(destinationFile);
                
            }catch(IOException e){
                JOptionPane.showMessageDialog(jButton1, "Something went Wrong", "Warning Message", JOptionPane.WARNING_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public JTextField getPrImagePathInput() {
        return prImagePathInput;
    }

    private void showImage(File imageFile){
    
        ProductImage pimg = new ProductImage();
        ImageIcon icon = new ImageIcon(imageFile.getAbsolutePath());
        Image image = icon.getImage().getScaledInstance(140, 180, Image.SCALE_SMOOTH);
        boolean isset = pimg.setProductImage(new ImageIcon(image));
        if(isset){
          imageLoadingPanel.add(pimg);
            SwingUtilities.updateComponentTreeUI(imageLoadingPanel);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel imageLoadingPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField prImagePathInput;
    // End of variables declaration//GEN-END:variables
}
